package com.example.demo.enumeration;

public enum CardRarity {
    COMMON, RARE, SUPER_RARE, ULTRA_RARE, ULTIMATE_RARE, GHOST_RARE, STARLIGHT_RARE,
    PARALLEL_RARE, SECRET_RARE, PRISMATIC_SECRET_RARE, THE25TH_ANNIVERSARY_SECRET_RARE
}
